name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 (or desired version)
        uses: actions/setup-java@v4
        with:
          java-version: "17"  # Use a supported LTS version like Java 17
          distribution: "corretto"
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build  # Use 'build' for a more comprehensive build
      - name: Upload Build Artifacts (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/  # Upload the entire 'build' directory
